name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:      # lets you run it manually from the Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (dark palette, yellow snake)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Generate ONLY ONE file so you see ONLY ONE snake
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23FFD700

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
